version: '3'
services:
  app:
    container_name: tinyurl
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api_test:/usr/src/app
    depends_on:
      - postgres
    networks:
      - fullstack


  postgres:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5555:5432'
    volumes:
      - database_postgres_test:/var/lib/postgresql/data
    networks:
      - fullstack

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "5050:80"
    networks:
      - fullstack
    restart: unless-stopped

volumes:
  api_test:
  database_postgres_test:


networks:
  fullstack:
    driver: bridge
